### ISSUE TITLE
Guayas data missing in Ecuador GeoJSON file

### ISSUE THREAD

**Issue by dpaulsoria** [pablocarreraest/Ecuador-geoJSON#1]
**Issue Description:**
The coordinates for the Guayas province are missing or incorrect in the Ecuador GeoJSON file, resulting in no representation of the province in the visualizer.

**Steps to Reproduce:**
1. Open the visualizer.
2. Load the Ecuador GeoJSON file.
3. Observe the map where the Guayas province should be.

**Expected Behavior:**
The Guayas province should be properly represented on the map, displaying its boundaries and corresponding data.

**Actual Behavior:**
The Guayas province is missing or not displayed correctly, leading to an incomplete visualization of Ecuador.

**Additional Information:**
- The issue might be related to incorrect or missing coordinates for the Guayas province in the GeoJSON file.
- Please verify and update the coordinates for the Guayas province.

**Attachments:**
- Screenshot showing the missing Guayas province in the visualizer.

Thank you for looking into this issue.
![image](https://github.com/user-attachments/assets/eb808567-b28c-4522-8125-e04dd1f6a0c5)

**Comment by pabl-o-ce** [comment]
Guayas is a independent country now my friend

I think I fix it but I haven't use this map in a while if you can PR are open for fix

**Comment by dpaulsoria** [comment]
Sorry, but i don't think that Guayas is an independent country. That's wrong, please review your data sources

**Comment by pabl-o-ce** [comment]
it was a joke hehe I know.. I fix it but in a work I do it... you can fix it if wanna make a PR is very welcome. I don't have time for fix this right now maybe in the future

**Comment by dpaulsoria** [comment]
jajjajaj ok, let me see what i can do in this week

**Comment by pabl-o-ce** [comment]
let me see what can I do in this days also :)
happy coding sir
